name: 1.0$(rev:.r)
pr: none
trigger:
  branches:
    include:
    - release
    - develop
    - feature/*
  paths:
    exclude:
    - README.md
    - tf/README.md
  batch: true
stages:
- stage: build
  displayName: Build, Analyze, and Publish Artifacts
  jobs:
  - template: templates/build-job.yaml
    parameters:
      servicename: 'ffadmin'
      npm_command: ci
      artifactory_endpoint: Artifactory

- stage: Release_Development
  displayName: Release To Development
  dependsOn: build
  condition: and(succeeded(), or(eq(variables['build.sourceBranch'], 'refs/heads/develop'), eq(variables['build.sourceBranch'], 'refs/heads/release')))
  jobs:
  - template: templates/deploy.yaml
    parameters:
      job_name: Deploy_Dev
      servicename: 'ffadmin'
      svc_conn: 'IT Infrastructure Apps Dev (6213e05a-d0ed-4bcb-8ba9-e7c32d78b201)'
      env: dev
      group: InfraVar-Dev
      tfversion: '0.14.6'
- stage: Release_Production
  displayName: Release To Production
  dependsOn: Release_Development
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/release'))
  jobs:
    - template: templates/deploy.yaml
      parameters:
        job_name: Deploy_Prod
        servicename: 'ffadmin'
        svc_conn: 'IT Infrastructure Apps Prod (a7b1e7e0-020d-44d1-b0b9-759379b7cbfc)'
        env: prd
        group: InfraVar-Prd
        tfversion: '0.14.6'