import "reflect-metadata";
import { Container } from "inversify";
import { TYPES } from "./shared/inversify/types";
import { AppConfigService } from "./shared/service/appconfig/appconfig.service";
import { AppConfigServiceImpl } from "./shared/service/appconfig/appconfigimpl.service";
import { AppInsightsService } from "./shared/service/monitoring/applicationInsights";
import { CustomLogger } from "./shared/utils/customLogger.service";
import { CustomLoggerImpl } from "./shared/utils/customLoggerImpl.service";
import { CustomValidator } from "./shared/validators/customValidator";
import { CustomValidatorImpl } from "./shared/validators/customValidatorImpl";
import { DbConnectionService } from "./shared/service/databaseConfig/databaseConn.service";
import { KeyVaultService } from "./shared/service/keyvault/keyvault.service";
import { KeyVaultServiceImpl } from "./shared/service/keyvault/keyvaultImpl.service";
import { Utility } from "./shared/utils/utilityImpl.service";
import { UtilityService } from "./shared/utils/utility.service";
import { StatusInfoService } from "./HealthCheck/service/statusinfoservice.service";
import { StatusInfoServiceImpl } from "./HealthCheck/service/statusinfoserviceimpl.service";
import { Banners, BannerService } from "./shared/service/banner/bannerService";
import { BannerDataAccess, BannerDataService } from "./shared/service/banner/repository/bannerDataAccess";
import { GroupDataAccess } from "./shared/service/groups/repository/groupDataAccess";
import { CampaignGroupDataAccess } from "./shared/service/groups/repository/campaignGroupDataAccess";
import { GroupService } from "./shared/service/groups/group";
import { CampaignGroupService } from "./shared/service/groups/campaignGroup";
import { HelpFaqDataAccess, HelpFaqDataService } from "./shared/service/helpFaq/repository/helpFaqDataAccess";
import { HelpFaq, HelpFaqService } from "./shared/service/helpFaq/helpFaqService";
import { LoanOfficerDataAccess, LoanOfficerDataService } from "./shared/service/loanOfficer/repository/loanOfficerDataAccess";
import { LoanOfficerService } from "./LoanOfficer/service/LoanOfficer.service";
import { LoanOfficerServiceImpl } from "./LoanOfficer/service/LoanOfficerImpl.service";
import { LOByNameService } from "./LoanOfficerByName/service/LOByName.service";
import { LOByNameServiceImpl } from "./LoanOfficerByName/service/LOByNameImpl.service";
import { UpdateLoGroupService, UpdateLoService } from "./UpdateLoGroup/service/updateLoGroup";

const container = new Container();

container.bind<AppConfigService>(TYPES.AppConfigService).to(AppConfigServiceImpl).inSingletonScope();
container.bind<AppInsightsService>(TYPES.AppInsightsService).to(AppInsightsService).inSingletonScope();
container.bind<CustomLogger>(TYPES.CustomLogger).to(CustomLoggerImpl).inSingletonScope();
container.bind<CustomValidator>(TYPES.CustomValidator).to(CustomValidatorImpl).inSingletonScope();
container.bind<DbConnectionService>(TYPES.DbConnectionService).to(DbConnectionService).inSingletonScope();
container.bind<KeyVaultService>(TYPES.KeyVaultService).to(KeyVaultServiceImpl).inSingletonScope();
container.bind<UtilityService>(TYPES.UtilityService).to(Utility).inSingletonScope();
container.bind<StatusInfoService>(TYPES.StatusInfoService).to(StatusInfoServiceImpl).inSingletonScope();
container.bind<BannerService>(TYPES.BannerService).to(Banners).inSingletonScope();
container.bind<BannerDataService>(TYPES.BannerDataService).to(BannerDataAccess).inSingletonScope();
container.bind<GroupDataAccess>(TYPES.CampaignGroupDataAccess).to(CampaignGroupDataAccess).inSingletonScope();
container.bind<GroupService>(TYPES.CampaignGroupService).to(CampaignGroupService).inSingletonScope();
container.bind<HelpFaqDataService>(TYPES.HelpFaqDataService).to(HelpFaqDataAccess).inSingletonScope();
container.bind<HelpFaqService>(TYPES.HelpFaqService).to(HelpFaq).inSingletonScope();
container.bind<LoanOfficerDataService>(TYPES.LoanOfficerDataService).to(LoanOfficerDataAccess).inSingletonScope();
container.bind<LoanOfficerService>(TYPES.LoanOfficerServiceImpl).to(LoanOfficerServiceImpl).inSingletonScope();
container.bind<LOByNameService>(TYPES.LOByNameServiceImpl).to(LOByNameServiceImpl).inSingletonScope();
container.bind<UpdateLoService>(TYPES.UpdateLoService).to(UpdateLoGroupService).inSingletonScope();

export { container };
