
subscipt: infapp
service: ffadmin
default_tags:
  service-product: Fairway First Admin API
  costcenter: 1151
  data-classification: Private
  Owner-email: jessica.manna@fairwaymc.com
  pid: n/a
  Expiration: n/a