
subscipt: infapp
service: service-name
default_tags:
  service-product: Function Application
  costcenter: 1070
  data-classification: Private
  Owner-email: username@fairwaymc.com
  pid: n/a
  Expiration: n/a
