const TYPES = {
    AppConfigService: Symbol.for("AppConfigService"),
    AppInsightsService: Symbol.for("AppInsightsService"),
    CustomLogger: Symbol.for("CustomLogger"),
    CustomValidator: Symbol.for("CustomValidator"),
    DbConnectionService: Symbol.for("DbConnectionService"),
    KeyVaultService: Symbol.for("KeyVaultService"),
    UtilityService: Symbol.for("UtilityService"),
    EmailServiceImpl: Symbol.for("EmailServiceImpl"),
    ServiceBusService: Symbol.for("ServiceBusService"),
    GetDashBoardImpl: Symbol.for("GetDashBoardImpl"),
    GetDashBoardDaoImpl: Symbol.for("GetDashBoardDaoImpl"),
    SendToHomeBirdImpl: Symbol.for("SendToHomeBirdImpl"),
    LeadFilterServiceImpl: Symbol.for("LeadFilterServiceImpl"),
    LeadsServiceImpl: Symbol.for("LeadsServiceImpl"),
    LoanOfficerService: Symbol.for("LoanOfficerService"),
    LOByNameServiceImpl: Symbol.for("LOByNameServiceImpl"),
    GetLeadServiceImpl: Symbol.for("GetLeadServiceImpl"),
    UpdateLeadInfoImpl: Symbol.for("UpdateLeadInfoImpl"),
    AnalyticsServiceImpl: Symbol.for("AnalyticsServiceImpl"),
    CampaignGroupDataAccess: Symbol.for("CampaignGroupDataAccess"),
    CampaignGroupService: Symbol.for("CampaignGroupService"),
    LoanOfficerDataService: Symbol.for("LoanOfficerDataService"),
    LeadDataService: Symbol.for("LeadDataService"),
    UpdateLoService: Symbol.for("UpdateLoService"),
    HelpFaqDataService: Symbol.for("HelpFaqDataService"),
    HelpFaqService: Symbol.for("HelpFaqService"),
    BannerService: Symbol.for("BannerService"),
    BannerDataService: Symbol.for("BannerDataService"),
    TimelineService: Symbol.for("TimelineService"),
    ExportLeadsServiceImpl: Symbol.for("ExportLeadsServiceImpl"),
    JSONHelper: Symbol.for("JSONHelper"),
    RelationshipDataService: Symbol.for("RelationshipDataService"),
    RelationshipService: Symbol.for("RelationshipService"),
    BigQueryService: Symbol.for("BigQueryService"),
    RelationshipHtmlService: Symbol.for("RelationshipHtmlService"),
    LeadsFilterOptionsService: Symbol.for("LeadsFilterOptionsService"),
    LeadsFilterOptionsServiceImpl: Symbol.for("LeadsFilterOptionsServiceImpl"),
};

export { TYPES };
