environment: dev
subscription_id: 6213e05a-d0ed-4bcb-8ba9-e7c32d78b201
spn_id: 54f58b4a-bf74-411d-9372-279fcdb5f17a
spn_oid: 14863280-33ca-4fae-a8bb-2d35b0dc3142
tags:
    pid: n/a
    Expiration: n/a
    Environment: Development

rbac_enabled: 1
adls: /subscriptions/6213e05a-d0ed-4bcb-8ba9-e7c32d78b201/resourceGroups/rg-fim-infapp-dev-cus-dataauto/providers/Microsoft.Storage/storageAccounts/dlsfimappdevcusdataauto
log_analytics: law-fim-infapp-dev-cus
log_analytics_rg: rg-fim-infapp-dev-core

datalake_account_name: "dlsfimappdevcusdataauto"
datalake_mktg_integrations_folder_path: "raw/mktg/dev/integrations/"
datalake_flowapi_folder: "flowapi"
datalake_mailchimp_folder: "mailchimp"
datalake_totalexpert_folder: "totalexpert"
datalake_workfront_folder: "workfront"
mailchimp_api_base_url: "https://us12.api.mailchimp.com/3.0"
mailchimp_list_id: "fa3d2642fe"
mailchimp_operation_id: "fairway_adf_batch_update"
mailchimp_email_error_to: "chandra.mandadi@fairwaymc.com"
mailchimp_email_error_subject: "Fairway Local Environment | Workday To Mailchimp Sync - Error"
mailchimp_email_report_to: "chandra.mandadi@fairwaymc.com"
mailchimp_email_report_from: "no-reply@fairwaymc.com"
mailchimp_email_report_subject: "Fairway Local Environment | Workday To Mailchimp Sync"
inactive_users_days_ago: "30"
workfront_email_error_to: "chandra.mandadi@fairwaymc.com"
workfront_email_error_subject: "Fairway Local Environment | Workday To Workfront Sync - Error"
workfront_email_report_to: "chandra.mandadi@fairwaymc.com"
workfront_email_report_from: "no-reply@fairwaymc.com"
workfront_email_report_subject: "Fairway Local Environment | Workday To Workfront Sync"
totalexpert_email_error_to: "chandra.mandadi@fairwaymc.com"
totalexpert_email_error_subject: "Fairway Local Environment | Workday To TotalExpert Sync - Error"
totalexpert_email_report_to: "chandra.mandadi@fairwaymc.com"
totalexpert_email_report_from: "no-reply@fairwaymc.com"
totalexpert_email_report_subject: "Fairway Local Environment | Workday To TotalExpert Sync"
webdata_url: "https://fairway-api-access.s3.amazonaws.com/js/tmp/webflow_data_sync/new_flow/fairway-flow-data-withweb.json"

fn_kind: functionapp
fn_tier: Dynamic
fn_size: Y1
pre_warmed_instance_count: 0
asp_reserved: false
os_type:
function_timeout: 00:10:00
elastic_instance_minimum:
